workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-8
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/peaceful-basis-411414/artifact-repo/train-model:latest
      env:
        - name: WANDB_API_KEY
          value: "3a8227d16fffba40e5a4f21fbe96329c602fac69"