default_model:
  driver: "default_model"
  seed: 42
  paths:
    train_dataset: "data/processed/train_dataset.pt"
    test_dataset: "data/processed/test_dataset.pt"
    model_checkpoint: "src/models/checkpoints/model_all_data_epoch_10_lr_0.001.pt"

  hyperparams:
    num_classes: 6
    learning_rate: 0.001
    batch_size: 64

  wandb_project: "emotion_detection"