ame: Docker Image CI

on:
    push:
        branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: DVC pull
        run: dvc pull 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push trainer
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: train-model:latest
          file: dockerfiles/train_model.dockerfile
        
      - name: 'gcr.io/cloud-builders/docker'
          args: ['build', '-t', 'gcr.io/peaceful-basis-411414/train-model:latest', '.']
      - name: 'gcr.io/cloud-builders/docker'
          args: ['push', 'gcr.io/peaceful-basis-411414/train-model:latest']