name: Docker Image CI

on:
  push:
    branches:
      - remote_storage
      - main
  pull_request:
    branches:
      - remote_storage
      - main

    #push:
    #    branches: [ main ]

steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-central1-docker.pkg.dev/peaceful-basis-411414/artifact-repo/train-model:latest', '--file', './dockerfiles/train_model.dockerfile', '.']
    # env: 
    # - 'DOCKER_BUIDKIT=1'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/peaceful-basis-411414/artifact-repo/train-model:latest']
      
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-central1-docker.pkg.dev/peaceful-basis-411414/artifact-repo/predict-model:latest', '--file', './dockerfiles/predict_model.dockerfile', '.']
    # env: 
    # - 'DOCKER_BUIDKIT=1'
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/peaceful-basis-411414/artifact-repo/predict-model:latest'] 
