name: Docker Image CI

on:
    push:
        branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push trainer
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}/trainer_image:$GITHUB_SHA
          file: dockerfiles/train_model.dockerfile


      # - name: Build the Docker image
      #   run: |
      #     echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
      #         -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
      #     docker build . --file dockerfiles/train_model.dockerfile \ 
      #         --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
      #     docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA