name: Docker Image CI

on:
  push:
    branches:
      - remote_storage
      - main
  pull_request:
    branches:
      - remote_storage
      - main

    #push:
    #    branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        with:
          #project_id: ${{ secrets.GC_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Install DVC-GS for Google Cloud Storage support
        run: |
          pip install dvc
          pip install dvc-gs
          pip install -U dvc dvc[gs]
      
      - name: Pull data from GCS via DVC
        run: |
          dvc pull
      #- uses: iterative/setup-dvc@v1
      #- name: DVC pull
      #  run: dvc pull 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push trainer
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: emotion-detection:latest
          file: dockerfiles/train_model.dockerfile
        
      


      # - name: Build the Docker image
      #   run: |
      #     echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
      #         -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
      #     docker build . --file dockerfiles/train_model.dockerfile \ 
      #         --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
      #     docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA