name: "Run tests"

on:
  push:
    branches:
      - remote_storage
      - main
  pull_request:
    branches:
      - remote_storage
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTEST_ROOT_DIR: ${{ github.workspace }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ubuntu-latest-py3.10-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ubuntu-latest-py3.10-pip-

      - uses: 'google-github-actions/auth@v2'
        with:
          #project_id: ${{ secrets.GC_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Upgrade setup-gcloud action
      #   run: |
      #     gcloud auth configure-docker

      # - name: Install DVC-GS for Google Cloud Storage support
      #   run: |
      #     pip install dvc
      #     pip install dvc-gs
      #     pip install -U dvc dvc[gs]

      # - name: Install DVC and Pull Data  # Updated name
      #   run: |
      #     pip install -U dvc dvc[gs]
      #     git init
      #     dvc pull

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_tests.txt
          pip install pytest-mock 

      - name: Pull data from GCS via DVC
        run: |
          dvc pull data/processed/train_dataset.pt
          dvc pull data/processed/test_dataset.pt

      - name: Download Latest Model Checkpoint from GCS
        run: |
          gsutil cp $(gsutil ls gs://data_tensors/*.ckpt | sort | tail -1) ./model.ckpt
    
      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v
          
